#!/bin/sh

set -e

etwork_CONFIGURATION_FILE=/etc/etwork/etwork.conf
etwork_GROUP="etwork"
etwork_DATA_DIR=/var/lib/etwork
etwork_LOG_DIR=/var/log/etwork
etwork_USER="etwork"

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^etwork:"; then
            adduser --system --home $etwork_DATA_DIR --quiet --group $etwork_USER
            # Data dir
            chown $etwork_USER:$etwork_GROUP $etwork_DATA_DIR
        fi
        # Register "$etwork_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $etwork_USER" 2> /dev/null || true
        # Configuration file
        chown $etwork_USER:$etwork_GROUP $etwork_CONFIGURATION_FILE
        chmod 0640 $etwork_CONFIGURATION_FILE
        # Log
        mkdir -p $etwork_LOG_DIR
        chown $etwork_USER:$etwork_GROUP $etwork_LOG_DIR
        chmod 0750 $etwork_LOG_DIR
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
