#!/bin/sh

set -e

etwork_LIB_DIR=/var/lib/etwork
etwork_USER="etwork"
etwork_GROUP="etwork"

case "${1}" in
    remove)
        deluser --quiet --system $etwork_USER || true
        delgroup --quiet --system --only-if-empty $etwork_GROUP || true
        ;;

    purge)
        if [ -d "$etwork_LIB_DIR" ]; then
            rm -rf $etwork_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
